import Head from "next/head";
import styles from "../styles/Home.module.css";
// COMPONENTS
import { Nav } from "../components/Header";

export default function Home() {
  return (
    <div className={styles.tag}>
      <Head>
        <title>flimes, séries e muito mais!</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/muflix.svg" />
      </Head>
      <header>
        <Nav />
      </header>
      <main>
        <div className={styles.banner}>
          <div className={styles.banner_contents}>
            <div className={styles.banner_texts}>
              <h1>
                Filmes, séries
                <br /> e muito mais.
                <br /> Sem limites.
              </h1>
              <p>
                Assine onde quiser.
                <br /> Cancele quando quiser.
              </p>
              <a href="#">Assinar</a>
            </div>
            <div className={styles.banner_form}></div>
          </div>
        </div>
      </main>
    </div>
  );
}
